apiVersion: v1
kind: Service
metadata:
  name: whistleblowing-service
spec:
  selector:
    app: whistleblowing-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8443
    protocol: TCP
    name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whistleblowing-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whistleblowing-app
  template:
    metadata:
      labels:
        app: whistleblowing-app
    spec:
      containers:
      - name: whistleblowing-app
        image: dahtach/whistleblowing
        ports:
        - containerPort: 8080
        - containerPort: 8443
